### PR TITLE
Add a dialog when downloading a log

### PR DESCRIPTION
**Pull request by elafargue**
Instead of having the Onyx device freeze, display a dialog. This uses the stock dialog display routine though it would look nicer with a dialog that does not state "Press a Key" at the bottom. But at least, this is a significant improvement on previous versions.

Corrected formatting for low battery routing in main.cpp

Added compatibility with firmware upload on Mavericks if anyone develops on a Mac - I do.

### CODE REVIEW

**Comment by thinrope** [comment]
There is a chance that it is my toolchain to blame, but after this I cannot build the firmware, code doesn't fit:

/home/kalin/Safecast/gcc-arm-none-eabi/arm/bin/../lib/gcc/arm-none-eabi/4.4.1/../../../../arm-none-eabi/bin/ld: safecast.elf section `.data' will not fit in region `rom'
/home/kalin/Safecast/gcc-arm-none-eabi/arm/bin/../lib/gcc/arm-none-eabi/4.4.1/../../../../arm-none-eabi/bin/ld: region `rom' overflowed by -1612 bytes
collect2: ld returned 1 exit status
Makefile:63: recipe for target 'safecast.elf' failed

$ arm-none-eabi-ld -v
GNU ld (Sourcery G++ Lite 2010q1-188) 2.19.51.20090709

Giving it a KB more seems to fix this, but I have no idea if that will break something else. We seem to be using 2KB flash pages, so I added 2KB to make it 494K on https://github.com/Safecast/onyxfirmware/blob/master/firmware/linker_files/safecast_flash.ld#L11

Can anyone check on my logic?

**Comment by elafargue** [comment]
I'll test & report on my own machine

**Comment by elafargue** [comment]
Master is compiling fine on my machine. What branch were you using for your tests ?

arm-none-eabi-g++ (GCC) 4.4.1
arm-none-eabi-ld --version
GNU ld (GNU Binutils) 2.19.51.20090709

**Comment by thinrope** [comment]
I was using master. Did even `git bisect` and all was fine before this merge.
Just reconfirmed that elafargue/onyxfirmware at 8f93b3d has the same issue from a clean clone.
May be there is something subtle in the environment (64bit?, kernel?), although using the same binary toolchain in theory should produce the same output...
(make-4.0, bash-4.2_p53)

Also, this seems related: https://github.com/sonomasoft/onyxfirmware/commit/8ee287d5487deec48d5b3eb0a48fc95471c201c2#diff-2

**Comment by elafargue** [comment]
I'm compiling on a Mac, Yosemite, a 64bit OS. So we do have exactly the same toolchain? Very strange! Since this is a cross-compilation, there is absolutely no reason why the host OS should have an impact. I'll try again from a clean checkout and report.

**Comment by elafargue** [comment]
OK, clean checkout is fine too.

The exact toolchain I am using is gcc-arm-none-eabi-latest-osx32-20130416.tar.gz . What's yours?

**Pull request merged**
